
[functions.delete-pilot-full]
enabled = true
verify_jwt = true
import_map = "./functions/delete-pilot-full/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-pilot-full/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-pilot-full/*.html" ]

[functions.create-pilot-with-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-pilot-with-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-pilot-with-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-pilot-with-user/*.html" ]
